main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path("", views.index, name='index'),
    path("docs", views.docs, name='docs'),
]

mawingu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
import requests
from django.contrib import messages

# Index page view


def index(request):
    if request.method == "POST":
        city = request.POST.get('city')

        try:
            url = "http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=fb25ed3367841cdd09348e1eedc1236c"

            # print(city)

            r = requests.get(url.format(city)).json()

            city_weather = {
                'city': city,
                'country': r['sys']['country'],
                'temperature': r['main']['temp'],
                'weather': r['weather'][0]['description'],
                'icon': r['weather'][0]["icon"],
                'feels_like': r['main']['feels_like'],
                'temp_min': r['main']['temp_min'],
                'temp_max': r['main']['temp_max'],
                'wind': r['wind']['speed'],
                'pressure': r['main']['pressure'],

            }

            context = {
                'city_weather': city_weather,
            }

            return render(request, "main/index.html", context)
        except:
            messages.error(request, "Please try entering a valid city!")
    else:
        pass

    # default weather to be shown on homepage before search
    city = 'Nairobi'
    url = "http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=fb25ed3367841cdd09348e1eedc1236c"

    r = requests.get(url.format(city)).json()

    city_weather = {
        'city': city,
        'country': r['sys']['country'],
        'temperature': r['main']['temp'],
        'weather': r['weather'][0]['description'],
        'icon': r['weather'][0]["icon"],
        'feels_like': r['main']['feels_like'],
        'temp_min': r['main']['temp_min'],
        'temp_max': r['main']['temp_max'],
        'wind': r['wind']['speed'],
        'pressure': r['main']['pressure'],
    }

    context = {
        'city_weather': city_weather,
    }

    return render(request, 'main/index.html', context)


# docs page view
def docs(request):
    return render(request, "main/docs.html")

main/templates/main/base.html
{% load static tailwind_tags %} {% load static %}
<!DOCTYPE html>
<html lang="en" class="w-100">
  <head>
    <title>Mawingu</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="shortcut icon"
      href="{% static 'img/clouds-fill.png' %}"
      type="image/x-icon"
    />
    {% tailwind_css %}
  </head>

  <body class="bg-blue-light font-serif leading-normal tracking-normal h-100">
    <!-- Navbar area -->
    <nav class="flex items-center justify-between p-6 shadow-md">
      <div class="flex items-center flex-shrink-0 text-blue-dark mr-6">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="35"
          height="35"
          fill="currentColor"
          class="bi bi-clouds-fill color-blue-dark"
          viewBox="0 0 16 16"
        >
          <path
            d="M11.473 9a4.5 4.5 0 0 0-8.72-.99A3 3 0 0 0 3 14h8.5a2.5 2.5 0 1 0-.027-5z"
          />
          <path
            d="M14.544 9.772a3.506 3.506 0 0 0-2.225-1.676 5.502 5.502 0 0 0-6.337-4.002 4.002 4.002 0 0 1 7.392.91 2.5 2.5 0 0 1 1.17 4.769z"
          />
        </svg>
        <a href="{% url 'main:index' %}">
          <span class="font-bold text-xl tracking-tight text-green-dark"
            >MAWINGU</span
          >
        </a>
      </div>
      <div class="block lg:hidden">
        <button
          class="flex items-center px-3 py-2 border rounded text-green-dark border-green-dark hover:text-blue-dark hover:border-blue-dark"
          onclick="menu()"
        >
          <svg
            class="fill-current h-3 w-3"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>Menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
          </svg>
        </button>
      </div>
      <div
        id="mobile"
        class="w-full block flex-grow lg:flex lg:items-center lg:w-auto lg:visible hidden"
      >
        <div
          class="font-semibold lg:flex-grow transition duration-500 ease-in-out"
        >
          <a
            href="#contact"
            class="block mt-4 lg:inline-block lg:mt-0 text-blue-dark hover:text-green-dark mr-4 disable"
            >contact</a
          >
          <a
            href="#about"
            class="block mt-4 lg:inline-block lg:mt-0 text-blue-dark hover:text-green-dark mr-4"
            >about</a
          >
          <a
            href="{% url 'main:docs' %}"
            class="block mt-4 lg:inline-block lg:mt-0 text-blue-dark hover:text-green-dark mr-4"
            >docs</a
          >
        </div>
      </div>
    </nav>
    {% for message in messages %}
    <p class="bg-red-default text-white-default p-4 m-2 rounded-lg">{{ message }}</p>
    {% endfor %}
    {% block content %}{% endblock content %}
    <footer class="justify-center flex text-sm text-center mt-64">
      <div>
        <p>
          Weather data provided by
          <a
            class="text-green-default"
            href="https://openweathermap.org"
            target="_blank"
            >OpenWeatherMap</a
          >
        </p>
        <p>
          2022&copy; made by
          <a
            class="text-green-default"
            href="https://barryimranapp.herokuapp.com"
            target="_blank"
            >Barrylabs</a
          >
        </p>
      </div>
    </footer>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
  </body>
</html>

main/templates/main/docs.html
 {% extends 'main/base.html' %}
  
  {% block content %}
  <p class="m-4">View my <a class="text-green-default" href="https://github.com/barissa-imran" target="_blank">Github</a> to see the docs for this project</p>
  <ul class="mx-16 list-decimal">
      <li>Django</li>
      <li>Tailwind CSS</li>
  </ul>
  {% endblock content %}

main/templates/main/index.html
{% extends 'main/base.html' %} {% block content %}
<!-- content section -->
<div class="flex text-blue-dark font-semibold p-6 mx-10 text-lg justify-center">
  <form method="post" class="flex">
    {% csrf_token %}
    <div>
      <div>
        <input
          type="text"
          name="city"
          id="city"
          class="form-control border-0 rounded-lg"
          placeholder="Search city"
          method="GET"
        />
      </div>
    </div>
    <div class="control">
        <button
          class="bg-blue-dark rounded-lg text-white-default mx-1 p-2 hover:bg-green-dark"
          type="submit"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-search m-1"
            viewBox="0 0 16 16"
          >
            <path
              d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"
            />
          </svg>
        </button>
      </div>
  </form>
</div>
<div class="flex justify-center">
<p id="time" class="m-2 text-green-dark"></p>
</div>
<!-- weather section -->
<div class="justify-center m-5 flex">
  <div class="shadow-md bg-white-default m-2 p-2 rounded-lg flex">
    <p><img src="http://openweathermap.org/img/w/{{city_weather.icon}}.png"></img></p>
    <div>
      <p class="font-bold">{{ city_weather.city }}, {{city_weather.country}}</p>
      <p>{{ city_weather.temperature| default:"Your search results will appear here" }}&deg;C</p>
      <p>{{ city_weather.weather }}</p>
    </div>
    
  </div>
  <div class="shadow-md bg-white-default m-2 p-2 rounded-lg">
    <p class="">
      Feels like: {{city_weather.feels_like| default:"Weather description will be shown here"}}&deg;C
    </p>
    <p class="">
      Max: {{city_weather.temp_max| default:"Weather description will be shown here"}}&deg;C
    </p>
    <p class="">
      Min: {{city_weather.temp_min| default:"Weather description will be shown here"}}&deg;C
    </p>
    <p class="">
      wind: {{city_weather.wind| default:"Weather description will be shown here"}} Km/hr
    </p>
  </div>
</div>

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>